// <auto-generated />
using System;
using AspNetCoreWebAPI8.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCoreWebAPI8.Migrations
{
    [DbContext(typeof(ProdContext))]
    partial class ProdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetCoreWebAPI8.Models.Product", b =>
                {
                    b.Property<int>("Product_Id")
                        .HasColumnType("int")
                        .HasColumnName("Product_Id");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("Rate");

                    b.Property<string>("TaxCode")
                        .HasColumnType("char(2)")
                        .HasColumnName("TaxCode");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.HasKey("Product_Id")
                        .HasName("PK_Product");

                    b.ToTable("Products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
